spring:

  datasource:
    url: jdbc:mysql://team9-database.cfeawoqw06q0.ap-northeast-2.rds.amazonaws.com:3306/ShoppingDB
    username: admin
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    aws:
      s3:
        bucket: team9-product-files

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    message: ${APP_MESSAGE}

logging:
  level:
    root: INFO
