spring:

  datasource:
    url: jdbc:mysql://localhost:3307/ShoppingDB
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    aws:
      s3:
        bucket: team9-product-files

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
